# Generated by Django 4.2.16 on 2024-10-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title/考试名称', max_length=20, verbose_name='考试名称')),
                ('student_number', models.CharField(max_length=20, verbose_name='学号')),
                ('student_name', models.CharField(help_text='name/姓名', max_length=20, verbose_name='姓名')),
                ('chinese_score', models.DecimalField(decimal_places=2, help_text='score/语文分数', max_digits=5, verbose_name='语文分数')),
                ('math_score', models.DecimalField(decimal_places=2, help_text='score/数学分数', max_digits=5, verbose_name='数学分数')),
                ('english_score', models.DecimalField(decimal_places=2, help_text='score/英语分数', max_digits=5, verbose_name='英语分数')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='grades.grade', verbose_name='班级')),
            ],
            options={
                'verbose_name': '成绩信息',
                'verbose_name_plural': '成绩信息',
                'db_table': 'score',
            },
        ),
    ]
